/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 arcade2.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/arcade2.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Arcade" position={[-1.491, -2.079, 1.362]} scale={0.395}>
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.Black} />
        <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Arcade screen']} />
        <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['Material.012']} />
        <mesh name="Plane003_3" geometry={nodes.Plane003_3.geometry} material={materials.Logo} />
      </group>
    </group>
  )
}

useGLTF.preload('/arcade2.gltf')
