/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 garage2.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/garage2.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Scene" />
    </group>
  )
}

useGLTF.preload('/garage2.gltf')
