"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 garage3.gltf -k 
*/

import { useGLTF, useScroll } from "@react-three/drei";
import React, { useRef, useLayoutEffect } from "react";
import { useFrame } from "@react-three/fiber";
import { useControls } from "leva";
import gsap from "gsap";
// import {SceneControl} from "./SceneControl"

export function Garage(props) {
  const group = useRef();
  const tl = useRef();
  const { nodes, materials, animations } = useGLTF("/models/garage3.gltf");

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
    // tl.current.seek(scroll * tl.current.duration);
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();
  
    // Première scène
    tl.current.fromTo(
      group.current.position,
      { x: -18.6, y: -16.8, z: -28.4 },
      { x: -1.4, y: -5.2, z: -2.0, duration: 1 },
      0
    );
    tl.current.fromTo(
      group.current.rotation,
      { y: 3.7 },
      { y: 0.5, duration: 1 },
      0
    );
  
    // Deuxième scène
    tl.current.fromTo(
      group.current.position,
      { x: -1.4, y: -5.2, z: -2.0 },
      { x: -0.1, y: -5.9, z: -4.8, duration: 1 },
      1
    );
    tl.current.fromTo(
      group.current.rotation,
      { y: 0.5 },
      { y: -0.95, duration: 1 },
      1
    );
  
    // Troisième scène
    tl.current.fromTo(
      group.current.position,
      { x: -0.1, y: -5.9, z: -4.8 },
      { x: 1.6, y: -6.2, z: 0.1, duration: 1 },
      2
    );
    tl.current.fromTo(
      group.current.rotation,
      { y: -0.95 },
      { y: -0.2, duration: 1 },
      2
    );

    // Quatrième scène (nouvelle scène ajoutée)
    tl.current.fromTo(
      group.current.position,
      { x: 1.6, y: -6.2, z: 0.1 },
      { x: -6.1, y: -6.1, z: -0.4, duration: 1 },
      3
    );
    tl.current.fromTo(
      group.current.rotation,
      { y: -0.2 },
      { y: 0.45, duration: 1 },
      3
    );
  });


  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      //   LEVA
      //position={[positionX, positionY, positionZ]}
      //rotation={[0, rotationY, 0]}
      position={[-6.8, -5.9, -7.6]}
      rotation={[0, -0.2, 0]}
    >
      <group name="Scene">
        <group
          name="Area001"
          position={[0, 7, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group
          name="Area"
          position={[0, 7, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          castShadow
          name="Point001"
          intensity={30}
          decay={2}
          color="#914fff"
          position={[-3.645, 1.659, -7.187]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          castShadow
          name="Point002"
          intensity={8}
          decay={2}
          color="#ff82f7"
          position={[-7.154, 1.798, -3.228]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          castShadow
          name="Point"
          intensity={30}
          decay={2}
          color="#ff9062"
          position={[2.852, 4.882, -1.896]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          receiveShadow
          name="_Room001"
          geometry={nodes._Room001.geometry}
          material={materials["Wall.001"]}
          position={[0, 0.336, 0]}
        />
        <group name="Arcade001" position={[-3.102, 0, 2.556]} scale={0.818}>
          <mesh
            castShadow
            name="Plane007"
            geometry={nodes.Plane007.geometry}
            material={materials["Black.001"]}
          />
          <mesh
            castShadow
            name="Plane007_1"
            geometry={nodes.Plane007_1.geometry}
            material={materials["Arcade screen.001"]}
          />
          <mesh
            castShadow
            name="Plane007_2"
            geometry={nodes.Plane007_2.geometry}
            material={materials["Glow.001"]}
          />
          <mesh
            castShadow
            name="Plane007_3"
            geometry={nodes.Plane007_3.geometry}
            material={materials["Logo.001"]}
          />
          <mesh
            castShadow
            name="Buttons002"
            geometry={nodes.Buttons002.geometry}
            material={materials["Yellow Glow.001"]}
            position={[0.814, 2.827, 0.268]}
            rotation={[0, 0, -0.244]}
          />
          <mesh
            castShadow
            name="Buttons003"
            geometry={nodes.Buttons003.geometry}
            material={materials["Yellow Glow.001"]}
            position={[0.814, 2.827, -1.039]}
            rotation={[0, 0, -0.244]}
          />
          <group
            name="Joystick002"
            position={[1.1, 2.821, 0.632]}
            rotation={[0, 0, -0.244]}
          >
            <mesh
              castShadow
              name="Circle001"
              geometry={nodes.Circle001.geometry}
              material={materials["Black.001"]}
            />
            <mesh
              castShadow
              name="Circle001_1"
              geometry={nodes.Circle001_1.geometry}
              material={materials["Red.001"]}
            />
          </group>
          <group
            name="Joystick003"
            position={[1.1, 2.821, -0.675]}
            rotation={[0, 0, -0.244]}
          >
            <mesh
              castShadow
              name="Circle001"
              geometry={nodes.Circle001.geometry}
              material={materials["Black.001"]}
            />
            <mesh
              castShadow
              name="Circle001_1"
              geometry={nodes.Circle001_1.geometry}
              material={materials["Red.001"]}
            />
          </group>
        </group>
        <mesh
          castShadow
          name="Shelving003"
          geometry={nodes.Shelving003.geometry}
          material={materials["Wood.003"]}
          position={[-4, 4.821, -2.204]}
        />
        <mesh
          castShadow
          name="Lamp001"
          geometry={nodes.Lamp001.geometry}
          material={materials["Red.001"]}
          position={[-3.505, 1.989, -1.612]}
          rotation={[0, 1.386, 0]}
          scale={1.204}
        >
          <pointLight
            name="Light001"
            intensity={2.712}
            decay={2}
            color="#ffb639"
            position={[-0.004, 1.048, 0.611]}
            rotation={[-Math.PI / 2, 0, -1.386]}
            scale={0.831}
          />
          <mesh
            castShadow
            name="Circle003"
            geometry={nodes.Circle003.geometry}
            material={materials["Red.001"]}
            position={[0, 1.212, 0.459]}
            rotation={[-0.751, 0, 0]}
            scale={0.735}
          >
            <mesh
              castShadow
              name="Icosphere001"
              geometry={nodes.Icosphere001.geometry}
              material={nodes.Icosphere001.material}
              position={[0, -0.209, 0]}
              rotation={[0.696, -1.228, 0]}
              scale={1.361}
            />
          </mesh>
          <mesh
            castShadow
            name="Vert001"
            geometry={nodes.Vert001.geometry}
            material={materials["Black.001"]}
            position={[0, 0.046, 0]}
          />
        </mesh>
        <mesh
          castShadow
          name="Keyboard002"
          geometry={nodes.Keyboard002.geometry}
          material={materials["Computer-beige.001"]}
          position={[-1.729, 2.026, -1.956]}
          rotation={[0, 0.707, 0]}
          scale={1.325}
        >
          <mesh
            castShadow
            name="Teclas003"
            geometry={nodes.Teclas003.geometry}
            material={materials["Grey.001"]}
            position={[-0.03, -0.001, 0.012]}
            rotation={[0.103, 0, 0]}
          />
        </mesh>
        <mesh
          castShadow
          name="Keyboard003"
          geometry={nodes.Keyboard003.geometry}
          material={materials["Computer-beige.001"]}
          position={[2.311, 2.742, -3.897]}
          rotation={[1.483, -Math.PI / 2, 0]}
          scale={1.325}
        >
          <mesh
            castShadow
            name="Teclas004"
            geometry={nodes.Teclas004.geometry}
            material={materials["Grey.001"]}
            rotation={[0.093, 0, 0]}
          />
        </mesh>
        <mesh
          castShadow
          name="Table002"
          geometry={nodes.Table002.geometry}
          material={materials["Wood.003"]}
          position={[-2.754, -0.174, -1.52]}
          rotation={[0, 1.571, 0]}
          scale={0.86}
        >
          <group
            name="Compact_computer001"
            position={[-1.514, 2.516, -0.56]}
            rotation={[0, -1.571, 0]}
            scale={1.163}
          >
            <mesh
              castShadow
              name="Plane021"
              geometry={nodes.Plane021.geometry}
              material={materials["Computer-beige.001"]}
            />
            <mesh
              castShadow
              name="Plane021_1"
              geometry={nodes.Plane021_1.geometry}
              material={materials["Screen-dos.001"]}
            />
            <group name="Plane018_1">
              <mesh
                castShadow
                name="Plane022_1"
                geometry={nodes.Plane022_1.geometry}
                material={materials["Black.001"]}
              />
              <mesh
                castShadow
                name="Plane022_2"
                geometry={nodes.Plane022_2.geometry}
                material={materials["Computer-beige.001"]}
              />
              <mesh
                castShadow
                name="Plane022_3"
                geometry={nodes.Plane022_3.geometry}
                material={materials["Grey.001"]}
              />
            </group>
            <mesh
              castShadow
              name="Teclas005"
              geometry={nodes.Teclas005.geometry}
              material={materials["Grey.001"]}
              position={[0.353, 0.172, -0.112]}
              rotation={[Math.PI / 2, 1.395, -Math.PI / 2]}
              scale={1.325}
            />
          </group>
          <mesh
            castShadow
            name="Computer002"
            geometry={nodes.Computer002.geometry}
            material={materials["Computer-beige.001"]}
            position={[1.619, 2.516, -0.229]}
            rotation={[0, -0.643, 0]}
            scale={1.423}
          >
            {/* <mesh castShadow
              name="Plane019_1"
              geometry={nodes.Plane019_1.geometry}
              material={materials["Computer-beige.001"]}
            /> */}
            {/* <mesh castShadow
              name="Plane020_1"
              geometry={nodes.Plane020_1.geometry}
              material={materials["Black.001"]}
              position={[0, 0, -0.102]}
            /> */}
            <mesh
              castShadow
              name="Plane021_2"
              geometry={nodes.Plane021_2.geometry}
              material={materials["Red.001"]}
              position={[0.402, 0.177, 0.422]}
              rotation={[-0.106, 0, 0]}
            />
            <group name="Plane022" position={[-0.448, 0.11, 0.426]}>
              <mesh
                castShadow
                name="Plane028"
                geometry={nodes.Plane028.geometry}
                material={materials["Computer-beige.001"]}
              />
              <mesh
                castShadow
                name="Plane028_1"
                geometry={nodes.Plane028_1.geometry}
                material={materials["Yellow Glow.001"]}
              />
            </group>
            <group name="Plane024_1" position={[-0.412, 0.11, 0.426]}>
              <mesh
                castShadow
                name="Plane028"
                geometry={nodes.Plane028.geometry}
                material={materials["Computer-beige.001"]}
              />
              <mesh
                castShadow
                name="Plane028_1"
                geometry={nodes.Plane028_1.geometry}
                material={materials["Yellow Glow.001"]}
              />
            </group>
            <group
              name="screen-nc001"
              position={[0.015, 0.265, 0.045]}
              scale={1.224}
            >
              <mesh
                castShadow
                name="Plane031"
                geometry={nodes.Plane031.geometry}
                material={materials["Computer-beige.001"]}
              />
              <mesh
                castShadow
                name="Plane031_1"
                geometry={nodes.Plane031_1.geometry}
                material={materials["Screen-nc.001"]}
              />
            </group>
          </mesh>
        </mesh>
        <mesh
          castShadow
          name="Table003"
          geometry={nodes.Table003.geometry}
          material={materials["Wood.003"]}
          position={[0.867, -0.174, -2.859]}
          scale={0.86}
        >
          <mesh
            castShadow
            name="Computer003"
            geometry={nodes.Computer003.geometry}
            material={materials["Computer-beige.001"]}
            position={[-2.027, 2.516, -0.691]}
            scale={1.423}
          >
            <mesh
              castShadow
              name="Plane047"
              geometry={nodes.Plane047.geometry}
              material={materials["Computer-beige.001"]}
            />
            <mesh
              castShadow
              name="Plane048"
              geometry={nodes.Plane048.geometry}
              material={materials["Black.001"]}
            />
            <mesh
              castShadow
              name="Plane050"
              geometry={nodes.Plane050.geometry}
              material={materials["Red.001"]}
              position={[0.402, 0.177, 0.422]}
              rotation={[-0.106, 0, 0]}
            />
            <group name="Plane051" position={[-0.448, 0.11, 0.426]}>
              <mesh
                castShadow
                name="Plane028"
                geometry={nodes.Plane028.geometry}
                material={materials["Computer-beige.001"]}
              />
              <mesh
                castShadow
                name="Plane028_1"
                geometry={nodes.Plane028_1.geometry}
                material={materials["Yellow Glow.001"]}
              />
            </group>
            <group name="Plane052" position={[-0.412, 0.11, 0.426]}>
              <mesh
                castShadow
                name="Plane028"
                geometry={nodes.Plane028.geometry}
                material={materials["Computer-beige.001"]}
              />
              <mesh
                castShadow
                name="Plane028_1"
                geometry={nodes.Plane028_1.geometry}
                material={materials["Yellow Glow.001"]}
              />
            </group>
            <group name="Plane053" position={[0.015, 0.265, 0.045]}>
              <mesh
                castShadow
                name="Plane033"
                geometry={nodes.Plane033.geometry}
                material={materials["Computer-beige.001"]}
              />
              <mesh
                castShadow
                name="Plane033_1"
                geometry={nodes.Plane033_1.geometry}
                material={materials["Screen-qb.001"]}
              />
            </group>
          </mesh>
          <mesh
            castShadow
            name="Patas001"
            geometry={nodes.Patas001.geometry}
            material={materials["Wood.003"]}
            position={[-7.267, 0, 3.276]}
            scale={1.182}
          />
          <mesh
            castShadow
            name="Raton001"
            geometry={nodes.Raton001.geometry}
            material={materials["Computer-beige.001"]}
            position={[-1.802, 2.516, 0.535]}
            scale={1.586}
          />
          <mesh
            castShadow
            name="TV001"
            geometry={nodes.TV001.geometry}
            material={materials["Black.001"]}
            position={[0.279, 2.516, -0.342]}
            rotation={[0, -0.174, 0]}
            scale={0.862}
          >
            <mesh
              castShadow
              name="Plane068"
              geometry={nodes.Plane068.geometry}
              material={materials["Grey.001"]}
              position={[-0.077, 1.275, -0.019]}
              rotation={[0, 0.061, 0]}
              scale={1.76}
            >
              <group name="Plane069">
                <mesh
                  castShadow
                  name="Plane068_1"
                  geometry={nodes.Plane068_1.geometry}
                  material={materials["Grey.001"]}
                />
                <mesh
                  castShadow
                  name="Plane068_2"
                  geometry={nodes.Plane068_2.geometry}
                  material={materials["Yellow Glow.001"]}
                />
              </group>
              <mesh
                castShadow
                name="Plane070"
                geometry={nodes.Plane070.geometry}
                material={materials["Black.001"]}
                position={[-0.171, 0.181, 0.294]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                castShadow
                name="Plane072"
                geometry={nodes.Plane072.geometry}
                material={materials["Black.001"]}
                position={[-0.001, 0, -0.115]}
              />
              <mesh
                castShadow
                name="Plane074"
                geometry={nodes.Plane074.geometry}
                material={materials["Grey.001"]}
              />
              <mesh
                castShadow
                name="Plane075_2"
                geometry={nodes.Plane075_2.geometry}
                material={materials["Black.001"]}
              />
              <mesh
                castShadow
                name="Plane076_2"
                geometry={nodes.Plane076_2.geometry}
                material={materials["Yellow Glow.001"]}
                position={[0.478, 0.028, 0.321]}
              />
              {/* <mesh castShadow
                name="Plane077_1"
                geometry={nodes.Plane077_1.geometry}
                material={materials["Black.001"]}
                position={[0.361, 0.313, 0.077]}
                rotation={[0, -0.316, 0]}
              /> */}
              <mesh
                castShadow
                name="Plane078"
                geometry={nodes.Plane078.geometry}
                material={materials["Black.001"]}
                position={[0.361, 0.257, 0.077]}
                rotation={[0, -0.5, 0]}
              />
            </mesh>
            <group name="Plane079_1" position={[0.73, 0.654, 0.528]}>
              <mesh
                castShadow
                name="Plane075"
                geometry={nodes.Plane075.geometry}
                material={materials["Black.001"]}
              />
              <mesh
                castShadow
                name="Plane075_1"
                geometry={nodes.Plane075_1.geometry}
                material={materials["Yellow Glow.001"]}
              />
            </group>
            <group name="Plane080_1">
              <mesh
                castShadow
                name="Plane076"
                geometry={nodes.Plane076.geometry}
                material={materials["Black.001"]}
              />
              <mesh
                castShadow
                name="Plane076_1"
                geometry={nodes.Plane076_1.geometry}
                material={materials["TV screen.001"]}
              />
            </group>
            {/* <mesh castShadow
              name="Plane081_1"
              geometry={nodes.Plane081_1.geometry}
              material={materials["Grey.001"]}
              position={[0, 0, -0.019]}
            /> */}
          </mesh>
        </mesh>
        <mesh
          castShadow
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[-3.68, 5.26, -2.188]}
          scale={0.352}
        />
        <mesh
          castShadow
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[4.502, 2.319, -2.816]}
          scale={0.352}
        />
        <mesh
          castShadow
          name="Table001"
          geometry={nodes.Table001.geometry}
          material={materials["Wood.006"]}
          position={[0.867, -0.174, -2.859]}
          scale={0.86}
        >
          <mesh
            castShadow
            name="Patas002"
            geometry={nodes.Patas002.geometry}
            material={materials["Wood.006"]}
            position={[3.804, 0.07, 0]}
            scale={1.182}
          />
        </mesh>
        <mesh
          castShadow
          name="Table004"
          geometry={nodes.Table004.geometry}
          material={materials["Wood.007"]}
          position={[0.867, -0.174, -2.859]}
          scale={0.86}
        >
          <mesh
            castShadow
            name="Patas003"
            geometry={nodes.Patas003.geometry}
            material={materials["Wood.007"]}
            position={[3.804, 0.07, -1.71]}
            scale={1.182}
          />
        </mesh>
        <mesh
          castShadow
          name="Table005"
          geometry={nodes.Table005.geometry}
          material={materials["Wood.008"]}
          position={[0.867, -0.174, -2.859]}
          scale={0.86}
        >
          <mesh
            castShadow
            name="Patas004"
            geometry={nodes.Patas004.geometry}
            material={materials["Wood.008"]}
            position={[-5.67, 0, -0.007]}
            scale={1.182}
          />
        </mesh>
        <mesh
          castShadow
          name="Table006"
          geometry={nodes.Table006.geometry}
          material={materials["Wood.009"]}
          position={[0.867, -0.174, -2.859]}
          scale={0.86}
        >
          <mesh
            castShadow
            name="Patas005"
            geometry={nodes.Patas005.geometry}
            material={materials["Wood.009"]}
            position={[-5.67, 0, 3.276]}
            scale={1.182}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/garage3.gltf");
