/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 garage5.gltf -k 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

//ADD CHARACTER ANIMATION

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/garage.gltf");

  return (
    <>
        <group {...props} dispose={null}>
      <group name="laptop" position={[-1.07, -1.1, -1.189]} rotation={[-Math.PI / 2, 0, -0.773]} scale={0.027}>
        <group name="lap" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="Cube008" position={[-589.006, 47.149, 958.996]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[705.172, 951.182, 49.909]}>
            <mesh name="Cube002_Material001_0" geometry={nodes.Cube002_Material001_0.geometry} material={materials['Material.017']} position={[0, 0.383, -14.967]} />
            <group name="Cube002_Material_0" position={[0, 0.383, -14.967]}>
              <mesh name="Cube002_Material_0_1" geometry={nodes.Cube002_Material_0_1.geometry} material={materials['Material.018']} />
              <mesh name="Cube002_Material_0_2" geometry={nodes.Cube002_Material_0_2.geometry} material={materials['Material.028']} />
            </group>
          </group>
        </group>
      </group>
      <group name="leaf014_7" position={[-1.268, 8.52, -0.525]} rotation={[-2.687, 1.381, 2.411]} scale={1.815}>
        <group name="Object_17" position={[0.111, -4.258, -0.673]} scale={0.117}>
          <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.leaf} />
          <mesh name="Object_7_1" geometry={nodes.Object_7_1.geometry} material={materials.ceramique} />
          <mesh name="Object_7_2" geometry={nodes.Object_7_2.geometry} material={materials.dirt} />
          <mesh name="Object_7_3" geometry={nodes.Object_7_3.geometry} material={materials.bark_i_dunno_i_guess_thats_how_its_called} />
        </group>
      </group>
      <mesh name="Ethereum_logo_@akimovcg" geometry={nodes['Ethereum_logo_@akimovcg'].geometry} material={materials['default']} position={[-0.491, -0.544, -1.471]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.494, -1.108, -1.471]} scale={[0.086, 0.043, 0.086]} />
      <mesh name="logo" geometry={nodes.logo.geometry} material={materials['Material.011']} position={[-1.431, 0.562, -1.881]} rotation={[Math.PI / 2, 0, 0]} scale={0.942} />
      <mesh name="star_trophy002" geometry={nodes.star_trophy002.geometry} material={materials.material} position={[1.224, -1.086, -1.367]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh name="trophy_L002" geometry={nodes.trophy_L002.geometry} material={materials.material} position={[1.224, -1.086, -0.939]} rotation={[Math.PI / 2, 0, 0]} scale={[0, 0, 0.001]} />
      <mesh name="trophy_M002" geometry={nodes.trophy_M002.geometry} material={materials.material} position={[0.836, -1.086, -0.939]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh name="trophy_S002" geometry={nodes.trophy_S002.geometry} material={materials.material} position={[0.475, -1.086, -0.939]} rotation={[Math.PI / 2, 0, 0]} scale={[0, 0, 0.001]} />
      <mesh name="trophy_M003" geometry={nodes.trophy_M003.geometry} material={materials.material} position={[0.836, -1.086, -1.319]} rotation={[Math.PI / 2, 0, -0.434]} scale={0.001} />
      <group name="Table001" position={[0.425, -2.164, -1.315]} scale={0.415}>
        <mesh name="Plane030" geometry={nodes.Plane030.geometry} material={materials['Material.003']} />
        <mesh name="Plane030_1" geometry={nodes.Plane030_1.geometry} material={materials['Material.009']} />
        <mesh name="Plane030_2" geometry={nodes.Plane030_2.geometry} material={materials['Material.006']} />
        <mesh name="Plane030_3" geometry={nodes.Plane030_3.geometry} material={materials['Material.007']} />
      </group>
      <mesh name="guy1" geometry={nodes.guy1.geometry} material={materials.bark_i_dunno_i_guess_thats_how_its_called} position={[-1.726, 0.297, -0.92]} rotation={[Math.PI / 2, 0, -0.594]} scale={0.35} />
      <mesh name="guy2" geometry={nodes.guy2.geometry} material={materials.leaf} position={[-1.758, 0.295, -1.715]} rotation={[Math.PI / 2, 0, -0.731]} scale={0.374} />
      <mesh name="guy3" geometry={nodes.guy3.geometry} material={materials.leaf} position={[-1.783, 0.29, -0.389]} rotation={[Math.PI / 2, 0, -0.616]} scale={0.374} />
      <mesh name="guy4" geometry={nodes.guy4.geometry} material={materials.material} position={[-1.782, 0.292, -1.334]} rotation={[1.552, 0.041, -1.137]} scale={0.374} />
      <mesh name="guy5" geometry={nodes.guy5.geometry} material={materials.dirt} position={[-1.871, 0.298, -0.727]} rotation={[Math.PI / 2, 0, -1.228]} scale={0.395} />
      <mesh name="robotArm" geometry={nodes.robotArm.geometry} material={materials.Material} position={[-1.482, -1.882, 0.066]} scale={0.628} />
      <group name="sword" position={[-0.969, -0.612, 0.227]} rotation={[-0.827, -0.163, -1.137]} scale={0.045}>
        <mesh name="Cube_0" geometry={nodes.Cube_0.geometry} material={materials['Material.029']} />
        <mesh name="Cube_0_1" geometry={nodes.Cube_0_1.geometry} material={materials['mango.001']} />
        <mesh name="Cube_0_2" geometry={nodes.Cube_0_2.geometry} material={materials.material} />
      </group>
      <mesh name="Shelving" geometry={nodes.Shelving.geometry} material={materials['Material.005']} position={[-1.925, 0.248, -0.998]} scale={0.483} />
      <group name="_Room" position={[-0.657, -0.891, -0.598]} scale={0.483}>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.036']} />
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
        <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
    </>
  );
}

useGLTF.preload("/models/garage.gltf");
