/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 garage5.gltf -k 
*/

import React, { useRef, useLayoutEffect, useEffect } from "react";
import { useGLTF, PerspectiveCamera, useScroll, CameraControls } from "@react-three/drei";
import { useKeyboard } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import gsap from "gsap";

const DEG45 = Math.PI / 4;

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/garage5.gltf");
//   const camera = useRef();
  const { viewport } = useThree();
  const responsiveRatio = viewport.width / 12;
  const officeScaleRatio = Math.max(0.8, Math.min(0.9 * responsiveRatio, 0.9));
  const isMobile = window.innerWidth < 768;

  const camera = useRef()
  const control = useRef()

  useEffect(() => {
    const logCameraCoordinates = () => {
      if (camera.current) {
        // Accessing the camera position and rotation from the ref
        const { position, rotation } = camera.current;
        console.log(`Camera Position: x=${position.x}, y=${position.y}, z=${position.z}`);
        console.log(`Camera Rotation: x=${rotation.x}, y=${rotation.y}, z=${rotation.z}`);
      }
    };

    logCameraCoordinates(); // Initial log
    const intervalId = setInterval(logCameraCoordinates, 1000); // Logs every 1 second

    return () => clearInterval(intervalId); // Cleanup the interval on component unmount
  }, []);

  return (
    <>
      {/* <PerspectiveCamera
        ref={camera}
        name="Camera"
        makeDefault={true}
        far={1000}
        near={0.1}
        fov={isMobile ? 50 : 30}
        position={[8.835, 6.434, 9.175]}
        rotation={[-0.644, 0.639, 0.421]}
      /> */}
      <CameraControls ref={control} >

      <PerspectiveCamera
        name="Camera"
        ref={camera}
        makeDefault={true}
        far={1000}
        near={0.1}
        fov={isMobile ? 50 : 30}
        position={[8.835, 6.434, 9.175]}
        rotation={[-0.644, 0.639, 0.421]}
      />
          </CameraControls>
      <group
        {...props}
        position={[isMobile ? 0 : 0, isMobile ? -viewport.height / 4 : 0, 0]}
        scale={[2,2,2]}
        dispose={null}
      >
        <pointLight
          name="Point001"
          intensity={100.957}
          decay={2}
          color="#914fff"
          position={[-0.839, -0.5, -1.684]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.241}
        />
        <pointLight
          name="Point002"
          intensity={10.946}
          decay={2}
          color="#ff82f7"
          position={[-1.686, -0.466, -0.729]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.241}
        />
        <pointLight
          name="Point"
          intensity={10.853}
          decay={2}
          color="#ff9062"
          position={[0.729, 0.278, -0.407]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.241}
        />
        <group name="_Room" position={[0.041, -0.819, 0.05]} scale={0.241}>
          <mesh
            name="Plane"
            geometry={nodes.Plane.geometry}
            material={materials.Wall}
          />
          <mesh
            name="Plane_1"
            geometry={nodes.Plane_1.geometry}
            material={materials.Floor}
          />
        </group>
        <group name="Arcade" position={[-0.708, -0.9, 0.699]} scale={0.197}>
          <mesh
            name="Plane003"
            geometry={nodes.Plane003.geometry}
            material={materials.Black}
          />
          <mesh
            name="Plane003_1"
            geometry={nodes.Plane003_1.geometry}
            material={materials["Arcade screen"]}
          />
          <mesh
            name="Plane003_2"
            geometry={nodes.Plane003_2.geometry}
            material={materials.Glow}
          />
          <mesh
            name="Plane003_3"
            geometry={nodes.Plane003_3.geometry}
            material={materials.Logo}
          />
          <mesh
            name="Buttons"
            geometry={nodes.Buttons.geometry}
            material={materials["Yellow Glow"]}
            position={[0.814, 2.827, 0.268]}
            rotation={[0, 0, -0.244]}
          />
          <mesh
            name="Buttons001"
            geometry={nodes.Buttons001.geometry}
            material={materials["Yellow Glow"]}
            position={[0.814, 2.827, -1.039]}
            rotation={[0, 0, -0.244]}
          />
          <group
            name="Joystick"
            position={[1.1, 2.821, 0.632]}
            rotation={[0, 0, -0.244]}
          >
            <mesh
              name="Circle"
              geometry={nodes.Circle.geometry}
              material={materials.Black}
            />
            <mesh
              name="Circle_1"
              geometry={nodes.Circle_1.geometry}
              material={materials.Red}
            />
          </group>
          <group
            name="Joystick001"
            position={[1.1, 2.821, -0.675]}
            rotation={[0, 0, -0.244]}
          >
            <mesh
              name="Circle"
              geometry={nodes.Circle.geometry}
              material={materials.Black}
            />
            <mesh
              name="Circle_1"
              geometry={nodes.Circle_1.geometry}
              material={materials.Red}
            />
          </group>
        </group>
        {/* <mesh name="Chair" geometry={nodes.Chair.geometry} material={materials.Metal} position={[0.089, -0.82, 0.082]} rotation={[0, -0.449, 0]} scale={0.282}>
        <mesh name="Circle015_1" geometry={nodes.Circle015_1.geometry} material={materials.Black} position={[0, 0.002, 0]} />
        <mesh name="Circle016" geometry={nodes.Circle016.geometry} material={materials.Red} position={[0, 1.406, 0]} scale={1.192}>
          <mesh name="Vert004" geometry={nodes.Vert004.geometry} material={materials.Black} rotation={[0, 1.548, 0]} scale={0.839} />
        </mesh>
      </mesh> */}
        <mesh
          name="Shelving"
          geometry={nodes.Shelving.geometry}
          material={materials.Wood}
          position={[-0.925, 0.264, -0.481]}
          scale={0.241}
        />
        {/* <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} /> */}
        <mesh
          name="Lamp"
          geometry={nodes.Lamp.geometry}
          material={materials.Red}
          position={[-0.805, -0.42, -0.339]}
          rotation={[0, 1.386, 0]}
          scale={0.291}
        >
          <pointLight
            name="Light"
            intensity={10.712}
            decay={2}
            color="#ffb639"
            position={[-0.004, 1.048, 0.611]}
            rotation={[-Math.PI / 2, 0, -1.386]}
            scale={0.831}
          />
          <mesh
            name="Circle017"
            geometry={nodes.Circle017.geometry}
            material={materials.Red}
            position={[0, 1.212, 0.459]}
            rotation={[-0.751, 0, 0]}
            scale={0.735}
          >
            <mesh
              name="Icosphere"
              geometry={nodes.Icosphere.geometry}
              material={nodes.Icosphere.material}
              position={[0, -0.209, 0]}
              rotation={[0.696, -1.228, 0]}
              scale={1.361}
            />
          </mesh>
          <mesh
            name="Vert005"
            geometry={nodes.Vert005.geometry}
            material={materials.Black}
            position={[0, 0.046, 0]}
          />
        </mesh>
        <mesh
          name="Keyboard"
          geometry={nodes.Keyboard.geometry}
          material={materials["Computer-beige"]}
          position={[-0.376, -0.411, -0.422]}
          rotation={[0, 0.707, 0]}
          scale={0.32}
        >
          <mesh
            name="Teclas"
            geometry={nodes.Teclas.geometry}
            material={materials.Grey}
            position={[-0.03, -0.001, 0.012]}
            rotation={[0.103, 0, 0]}
          />
        </mesh>
        <mesh
          name="Table"
          geometry={nodes.Table.geometry}
          material={materials.Wood}
          position={[-0.624, -0.942, -0.316]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.208}
        >
          <mesh
            name="Computer001"
            geometry={nodes.Computer001.geometry}
            material={materials["Computer-beige"]}
            position={[1.619, 2.516, -0.229]}
            rotation={[0, -0.643, 0]}
            scale={1.423}
          >
            <mesh
              name="Plane039"
              geometry={nodes.Plane039.geometry}
              material={materials["Computer-beige"]}
            />
            <mesh
              name="Plane042"
              geometry={nodes.Plane042.geometry}
              material={materials.Black}
              position={[0, 0, -0.102]}
            />
            <mesh
              name="Plane043"
              geometry={nodes.Plane043.geometry}
              material={materials.Red}
              position={[0.402, 0.177, 0.422]}
              rotation={[-0.106, 0, 0]}
            />
            <group name="Plane044" position={[-0.448, 0.11, 0.426]}>
              <mesh
                name="Plane038"
                geometry={nodes.Plane038.geometry}
                material={materials["Computer-beige"]}
              />
              <mesh
                name="Plane038_1"
                geometry={nodes.Plane038_1.geometry}
                material={materials["Yellow Glow"]}
              />
            </group>
            <group name="Plane045" position={[-0.412, 0.11, 0.426]}>
              <mesh
                name="Plane038"
                geometry={nodes.Plane038.geometry}
                material={materials["Computer-beige"]}
              />
              <mesh
                name="Plane038_1"
                geometry={nodes.Plane038_1.geometry}
                material={materials["Yellow Glow"]}
              />
            </group>
            <group
              name="screen-nc"
              position={[0.015, 0.265, 0.045]}
              scale={1.224}
            >
              <mesh
                name="Plane039_1"
                geometry={nodes.Plane039_1.geometry}
                material={materials["Computer-beige"]}
              />
              <mesh
                name="Plane039_2"
                geometry={nodes.Plane039_2.geometry}
                material={materials["Screen-nc"]}
              />
            </group>
          </mesh>
          <mesh
            name="Plane023"
            geometry={nodes.Plane023.geometry}
            material={materials.Wood}
            scale={1.182}
          />
        </mesh>
        <mesh
          name="Table001"
          geometry={nodes.Table001.geometry}
          material={materials.Wood}
          position={[0.25, -0.942, -0.64]}
          scale={0.208}
        >
          <mesh
            name="Patas"
            geometry={nodes.Patas.geometry}
            material={materials.Wood}
            scale={1.182}
          />
          <mesh
            name="Raton"
            geometry={nodes.Raton.geometry}
            material={materials["Computer-beige"]}
            position={[-1.802, 2.516, 0.535]}
            scale={1.586}
          />
        </mesh>
      </group>
    </>
  );
}

useGLTF.preload("/models/garage5.gltf");
