/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 logo.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { editable as e } from "@theatre/r3f";
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/logo.glb')
  const logoRef = useRef();

  // Créer des matériaux néon
  const neonMaterial1 = new THREE.MeshPhongMaterial({
    color: 0xf5f5dc,  // Couleur beige néon
    emissive: 0xf5f5dc,
    emissiveIntensity: 1.0,
    shininess: 100
  });

  const neonMaterial2 = new THREE.MeshPhongMaterial({
    color: 0xff0000,  // Couleur rouge néon
    emissive: 0xff0000,
    emissiveIntensity: 1.0,
    shininess: 100
  });


  return (
    <group {...props} dispose={null} ref={logoRef}>
      <e.group theatreKey="logo1" name="Cube" position={[-1.907, 0, 0.003]} scale={[1.898, 0.584, 0.617]}>
        <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={neonMaterial1} />
        <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={neonMaterial2} />
      </e.group>
      <e.group theatreKey="logo2" name="Cube002" position={[-1.907, 0, 0.003]} scale={[1.898, 0.584, 0.617]}>
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={neonMaterial1} />
        <mesh name="Cube025_1" geometry={nodes.Cube025_1.geometry} material={neonMaterial2} />
      </e.group>
      <pointLight position={[-1.907, 0, 1]} distance={3} intensity={2} color="#00ff00" />
      <pointLight position={[-1.907, 0, 1]} distance={3} intensity={2} color="#00ffff" />
    </group>
  )
}

useGLTF.preload('/models/logo.glb')
