/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 trophee.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/trophee.glb')
  return (
    <e.group theatreKey="trophees" {...props} dispose={null}>
      <mesh name="star_trophy_trophy1_0001" geometry={nodes.star_trophy_trophy1_0001.geometry} material={materials['trophy1.001']} position={[1.03, 0.254, 0.813]} rotation={[0, -1.148, 0]} scale={0} />
      <mesh name="trophy_L_trophy1_0001" geometry={nodes.trophy_L_trophy1_0001.geometry} material={materials['trophy1.001']} position={[0.945, 0.301, 0.943]} rotation={[0, 0.894, 0]} scale={0} />
      <mesh name="ball_trophy_trophy1_0001" geometry={nodes.ball_trophy_trophy1_0001.geometry} material={materials['trophy1.001']} position={[0.752, 0.282, 0.795]} scale={0} />
      <mesh name="trophy_M_trophy1_0001" geometry={nodes.trophy_M_trophy1_0001.geometry} material={materials['trophy1.001']} position={[0.895, 0.284, 0.686]} rotation={[-Math.PI, 0.97, -Math.PI]} scale={0} />
      <mesh name="trophy_S_trophy1_0001" geometry={nodes.trophy_S_trophy1_0001.geometry} material={materials['trophy1.001']} position={[0.778, 0.241, 0.894]} rotation={[0, 0.7, 0]} scale={0} />
      <mesh name="trophy_M_trophy1_0002" geometry={nodes.trophy_M_trophy1_0002.geometry} material={materials['trophy1.002']} position={[0.693, 0.258, 0.7]} rotation={[Math.PI, -0.829, Math.PI]} scale={0} />
    </e.group>
  )
}

useGLTF.preload('/models/trophee.glb')
